### ISSUE TITLE
Git lfs version 

### ISSUE THREAD

**Issue by davekds** [NVIDIA-ISAAC-ROS/.github#16]
I always get an Error: Error: Failed to call git rev-parse --git-dir: exit status 128

would be nice if you could mention the git lfs version? I have installed  2.9.2-1

**Comment by hemalshahNV** [comment]
The warning is actually not git-lfs related. The `run_dev.sh` script assumes that the parent directory of your ROS workspace directory is a git repository. That assumption is what causes the `git rev-parse` command to fail. It is innocuous but concerning. We have a fix for this coming in our next release however but for now, you can ignore it.

**Comment by davekds** [comment]
I fixed the problem by installing a newer version of git lfs (3.3.0) and had to install the NVIDIA Container Toolkit.
