### ISSUE TITLE
realsense-nvidia  solution won't reflect d457 camera

### ISSUE THREAD

**Issue by AndreV84** [NVIDIA-ISAAC-ROS/.github#21]
the realsense viewer  from within the container says no devices
https://github.com/NVIDIA-ISAAC-ROS/.github/blob/main/profile/realsense-setup.md
the viewer built without RSUSB outside the container lists the camera
any solution?

**Comment by hemalshahNV** [comment]
Isaac ROS provides RealSense support for you in [Dockerfile.realsense](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common/blob/main/docker/Dockerfile.realsense), but versions may be stale for such a new camera. 
 Please check on https://github.com/IntelRealSense/librealsense for any updates.
