### ISSUE TITLE
No camera frame!

### ISSUE THREAD

**Issue by BloodLemonS** [NVIDIA-ISAAC-ROS/.github#33]
After i open realsense-viewer and turn on RGB camera, there is no frames received! But when turn on stere module, it works well.
![image](https://github.com/NVIDIA-ISAAC-ROS/.github/assets/56753880/a3a98ea4-3305-4c00-884f-e0cd75787339)

**Comment by jaiveersinghNV** [comment]
Could you please provide more information about your setup? Which RealSense camera are you using? Which Jetson or discrete GPU are you using? Are you running inside the Isaac ROS container?

**Comment by BloodLemonS** [comment]
I use a realsense d455 and a laptop with GPU 3090. And I run inside the Isaac ROS container. The difference is that I use ubuntu 18.04 with ROS2 dashing.

**Comment by jaiveersinghNV** [comment]
Could you try running the RealSense viewer from the host, instead of inside the container? Right now, this looks like it could be an issue between the RealSense camera and the RealSense viewer, not an issue with Isaac ROS.

**Comment by BloodLemonS** [comment]
Hello, I can run realsense-viewer on the external terminal, which has color picture information

**Comment by jaiveersinghNV** [comment]
Could you please try the following steps:
1. With the RealSense **unplugged**, start the Docker container with `run_dev.sh`
2. After the container has started, plug in the RealSense D455 camera
3. After a few seconds, unplug the RealSense D455 camera.
4. Copy and upload the contents of `/tmp/docker_usb.log`

This log file will help us understand if the RealSense camera is being properly mounted into the container.
